package main

var smallLayout = layout{
	"name": &cell{
		x: 27, y: 13, w: 65, h: 8,
		align:      "LM",
		fontFamily: "Courier",
		fontSize:   12,
	},
	"profession": &cell{
		x: 27, y: 21, w: 65, h: 8,
		align:      "LM",
		fontFamily: "Courier",
		fontSize:   12,
	},
	"species": &cell{
		x: 27, y: 29, w: 65, h: 8,
		align:      "LM",
		fontFamily: "Courier",
		fontSize:   12,
	},
	"alien_ability": &cell{
		x: 27, y: 37, w: 65, h: 5,
		align:        "LM",
		fontFamily:   "Courier",
		fontSize:     10,
		fontWeight:   "I",
		overflowRows: 2,
	},

	"athletics": &cell{
		x: 107, y: 13, w: 17, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"combat": &cell{
		x: 107, y: 21, w: 17, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"engineering": &cell{
		x: 107, y: 29, w: 17, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"pilot": &cell{
		x: 107, y: 37, w: 17, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"science": &cell{
		x: 107, y: 45, w: 17, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},

	"base_hp": &cell{
		x: 138, y: 13, w: 19, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"hp": &cell{
		x: 171, y: 13, w: 32, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"move": &cell{
		x: 138, y: 21, w: 19, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"luck": &cell{
		x: 138, y: 29, w: 19, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"target": &cell{
		x: 138, y: 37, w: 19, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"hands": &cell{
		x: 138, y: 45, w: 19, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"rank": &cell{
		x: 171, y: 37, w: 32, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},
	"carry": &cell{
		x: 171, y: 45, w: 32, h: 8,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   16,
		fontWeight: "B",
	},

	"prestige": &cell{
		x: 40, y: 55, w: 32, h: 6,
		align:      "CR",
		fontFamily: "Courier",
		fontSize:   14,
		fontWeight: "I",
	},
	"experience": &cell{
		x: 105, y: 55, w: 32, h: 6,
		align:      "CR",
		fontFamily: "Courier",
		fontSize:   14,
		fontWeight: "I",
	},
	"credits": &cell{
		x: 170, y: 55, w: 32, h: 6,
		align:      "CR",
		fontFamily: "Courier",
		fontSize:   14,
		fontWeight: "I",
	},
	"sa.0.name": &cell{
		x: 7, y: 76, w: 30, h: 6,
		align:      "LM",
		fontFamily: "Courier",
		fontSize:   10,
		fontWeight: "B",
	},
	"sa.0.notes": &cell{
		x: 38, y: 76, w: 38, h: 6,
		align:      "LM",
		fontFamily: "Courier",
		fontSize:   8,
		fontWeight: "I",
	},
	"sa.0.pool": &cell{
		x: 76, y: 76, w: 12, h: 6,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   12,
		fontWeight: "B",
	},
	"sa.1.name": &cell{
		x: 7, y: 82, w: 30, h: 6,
		align:      "LM",
		fontFamily: "Courier",
		fontSize:   10,
		fontWeight: "B",
	},
	"sa.1.notes": &cell{
		x: 38, y: 82, w: 38, h: 6,
		align:      "LM",
		fontFamily: "Courier",
		fontSize:   8,
		fontWeight: "I",
	},
	"sa.1.pool": &cell{
		x: 76, y: 82, w: 12, h: 6,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   12,
		fontWeight: "B",
	},
	"sa.2.name": &cell{
		x: 7, y: 88, w: 30, h: 6,
		align:      "LM",
		fontFamily: "Courier",
		fontSize:   10,
		fontWeight: "B",
	},
	"sa.2.notes": &cell{
		x: 38, y: 88, w: 38, h: 6,
		align:      "LM",
		fontFamily: "Courier",
		fontSize:   8,
		fontWeight: "I",
	},
	"sa.2.pool": &cell{
		x: 76, y: 88, w: 12, h: 6,
		align:      "CM",
		fontFamily: "Courier",
		fontSize:   12,
		fontWeight: "B",
	},
}
